export const LOAD_BEGIN = "LOAD_BEGIN";
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOCATION = 'USER_LOCATION';
export const LOAD_FIREBASE_TOKEN = 'LOAD_FIREBASE_TOKEN';
export const DEVICE_ORIENTATION = 'DEVICE_ORIENTATION';
export const FORM_BUFFER = 'FORM_BUFFER';
export const USER_HISTORICO_LOAD = 'USER_HISTORICO_LOAD';